import 'dart:convert';

import 'package:shared_preferences/shared_preferences.dart';

import '../data/universe_history.dart';
import 'app_logger.dart';

/// Point-in-time Nifty index membership.
///
/// Answers "which stocks were in the Nifty 50/100/200/500 on date X?" so
/// backtests scan the universe as it actually was — removing the survivorship
/// bias of the static list (measured May-2022 vs current: only 352/500
/// overlap; a 2022 backtest on the static list has ~30% of its universe wrong).
///
/// Two snapshot sources, merged into one timeline per index:
///  1. BAKED (`UniverseHistoryData`, generated by
///     D:\Code\tools\universe-history\build_history.js from Wayback Machine
///     captures of the official NSE constituent CSVs) — covers the past.
///  2. RECORDED — every time [recordCurrent] sees today's fetched membership
///     differ from the last snapshot, it appends a dated snapshot to
///     SharedPreferences. The app archives index changes itself from now on,
///     so the baked file never needs regenerating for the future.
///
/// All historical symbols are pre-normalized (by the generator, via ISIN) to
/// their CURRENT NSE trading symbol, so they resolve against today's Dhan
/// scrip master. Delisted members (e.g. HDFC — ~10 names for 2022) keep their
/// old symbol, fail resolution downstream, and are logged+skipped: ~2%
/// residual bias vs ~30% before.
class UniverseHistory {
  UniverseHistory._();

  static const _prefsKey = 'universe_history_v1';

  static const modeStatic = 'static';
  static const modes = [modeStatic, 'nifty50', 'nifty100', 'nifty200', 'nifty500'];

  /// ScripService universe label for a mode (current-members resolution, live).
  static String universeLabel(String mode) => switch (mode) {
        'nifty50' => 'Nifty 50',
        'nifty100' => 'Nifty 100',
        'nifty200' => 'Nifty 200',
        _ => 'Nifty 500',
      };

  /// Human label for config UI.
  static String displayLabel(String mode) => switch (mode) {
        modeStatic => 'Static list (legacy)',
        'nifty50' => 'Nifty 50 — point-in-time',
        'nifty100' => 'Nifty 100 — point-in-time',
        'nifty200' => 'Nifty 200 — point-in-time',
        'nifty500' => 'Nifty 500 — point-in-time',
        _ => mode,
      };

  static bool _loaded = false;

  /// index key → snapshots sorted ascending by date.
  static final Map<String, List<({DateTime date, Set<String> symbols})>>
      _series = {};

  /// Recorded-only snapshots (persisted); merged into [_series] views.
  static final Map<String, List<({String date, List<String> symbols})>>
      _recorded = {};

  static Future<void> init() async {
    if (_loaded) return;

    List<({DateTime date, Set<String> symbols})> parse(
        Map<String, Set<String>> raw) {
      final list = raw.entries
          .map((e) => (date: DateTime.parse(e.key), symbols: e.value))
          .toList()
        ..sort((a, b) => a.date.compareTo(b.date));
      return list;
    }

    _series['nifty50'] = parse(UniverseHistoryData.nifty50);
    _series['niftyNext50'] = parse(UniverseHistoryData.niftyNext50);
    _series['niftyMidcap100'] = parse(UniverseHistoryData.niftyMidcap100);
    _series['nifty500'] = parse(UniverseHistoryData.nifty500);

    // Baked composites. Components before their first snapshot fall back to
    // that first snapshot (documented approximation — the top indices churn
    // slowly, so being months stale ≈ 2-4 names, not 30% of the universe).
    _series['nifty100'] = _composite(['nifty50', 'niftyNext50']);
    _series['nifty200'] = _composite(['nifty100', 'niftyMidcap100']);

    // Merge app-recorded snapshots (always newer than baked ones in practice;
    // sort handles any overlap).
    try {
      final prefs = await SharedPreferences.getInstance();
      final raw = prefs.getString(_prefsKey);
      if (raw != null && raw.isNotEmpty) {
        final decoded = jsonDecode(raw) as Map<String, dynamic>;
        for (final e in decoded.entries) {
          final entries = (e.value as List)
              .map((s) => (
                    date: s['d'] as String,
                    symbols: List<String>.from(s['s'] as List),
                  ))
              .toList();
          _recorded[e.key] = entries;
          final target = _series.putIfAbsent(e.key, () => []);
          for (final r in entries) {
            target.add((date: DateTime.parse(r.date), symbols: r.symbols.toSet()));
          }
          target.sort((a, b) => a.date.compareTo(b.date));
        }
      }
    } catch (e) {
      AppLogger.error('Universe', 'Failed to load recorded snapshots: $e');
    }

    _loaded = true;
    AppLogger.info(
      'Universe',
      'History loaded: ${modes.where((m) => m != modeStatic).map((m) => '$m=${_series[m]?.length ?? 0}').join(' ')} snapshot(s)',
    );
  }

  static List<({DateTime date, Set<String> symbols})> _composite(
      List<String> componentKeys) {
    final dates = <DateTime>{};
    for (final k in componentKeys) {
      for (final s in _series[k] ?? []) {
        dates.add(s.date);
      }
    }
    final sorted = dates.toList()..sort();
    return [
      for (final d in sorted)
        (
          date: d,
          symbols: {
            for (final k in componentKeys) ...?_lookup(_series[k], d)?.symbols,
          },
        ),
    ];
  }

  static ({DateTime date, Set<String> symbols})? _lookup(
      List<({DateTime date, Set<String> symbols})>? series, DateTime d) {
    if (series == null || series.isEmpty) return null;
    ({DateTime date, Set<String> symbols})? best;
    for (final s in series) {
      if (s.date.isAfter(d)) break;
      best = s;
    }
    // Before the first snapshot → use the first (pre-history approximation).
    return best ?? series.first;
  }

  /// Members of [mode]'s index as of [date]. Null for static mode / no data.
  /// Call [init] first (idempotent).
  static Set<String>? membersAsOf(String mode, DateTime date) {
    if (mode == modeStatic) return null;
    return _lookup(_series[mode], date)?.symbols;
  }

  /// Union of members across every snapshot regime touching [from]..[to] —
  /// the fetch/prep superset for a point-in-time backtest.
  static Set<String> unionOverRange(String mode, DateTime from, DateTime to) {
    final series = _series[mode];
    if (series == null || series.isEmpty) return {};
    final out = <String>{...?_lookup(series, from)?.symbols};
    for (final s in series) {
      if (!s.date.isBefore(from) && !s.date.isAfter(to)) out.addAll(s.symbols);
    }
    return out;
  }

  /// Self-recording: called after each successful daily NSE constituent fetch.
  /// Appends a dated snapshot per index whose membership changed since the
  /// last known snapshot (baked or recorded). This is what keeps the
  /// point-in-time system current forever without manual refreshes.
  static Future<void> recordCurrent(Map<String, Set<String>> byIndex) async {
    await init();
    final today = DateTime.now();
    final todayStr =
        '${today.year}-${today.month.toString().padLeft(2, '0')}-${today.day.toString().padLeft(2, '0')}';

    var changed = false;
    for (final e in byIndex.entries) {
      if (e.value.isEmpty) continue;
      final series = _series.putIfAbsent(e.key, () => []);
      final last = series.isEmpty ? null : series.last.symbols;
      if (last != null &&
          last.length == e.value.length &&
          last.containsAll(e.value)) {
        continue; // unchanged
      }

      final added = last == null ? e.value.length : e.value.difference(last).length;
      final removed = last == null ? 0 : last.difference(e.value).length;
      AppLogger.info('Universe',
          '${e.key} membership changed (+$added/−$removed) — snapshot recorded for $todayStr');

      series.add((date: today, symbols: Set.of(e.value)));
      (_recorded[e.key] ??= [])
          .add((date: todayStr, symbols: e.value.toList()..sort()));
      changed = true;
    }

    if (!changed) return;
    try {
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString(
        _prefsKey,
        jsonEncode({
          for (final e in _recorded.entries)
            e.key: [
              for (final s in e.value) {'d': s.date, 's': s.symbols},
            ],
        }),
      );
    } catch (e) {
      AppLogger.error('Universe', 'Failed to persist snapshot: $e');
    }
  }
}
