/// Nifty index-tier membership, derived from the four comment-delimited
/// sections of [Nifty500Stocks.symbols]. Auto-generated by
/// D:\Nearby\_lab_analysis\gen_tiers.js — do not hand-edit; regenerate if the
/// stock list changes. Used by the LAB strategy ONLY (mining dimension:
/// index-tier as a size/liquidity proxy). Additive — touches no existing code.
class NiftyTiers {
  NiftyTiers._();

  static const Set<String> nifty50 = {
    'RELIANCE', 'TCS', 'HDFCBANK', 'INFY', 'ICICIBANK', 'HINDUNILVR', 'ITC', 'SBIN', 'BHARTIARTL', 'KOTAKBANK',
    'LT', 'HCLTECH', 'AXISBANK', 'ASIANPAINT', 'MARUTI', 'SUNPHARMA', 'TITAN', 'BAJFINANCE', 'ULTRACEMCO', 'WIPRO',
    'NESTLEIND', 'BAJAJFINSV', 'ADANIENT', 'ONGC', 'NTPC', 'POWERGRID', 'TATAMOTORS', 'M&M', 'JSWSTEEL', 'TATASTEEL',
    'COALINDIA', 'TECHM', 'DIVISLAB', 'INDUSINDBK', 'ADANIPORTS', 'BAJAJ-AUTO', 'BRITANNIA', 'APOLLOHOSP', 'HINDALCO', 'GRASIM',
    'CIPLA', 'HEROMOTOCO', 'DRREDDY', 'BPCL', 'EICHERMOT', 'TATACONSUM', 'LTIM', 'TRENT', 'SBILIFE', 'HDFCLIFE',
  };

  static const Set<String> niftyNext50 = {
    'SHREECEM', 'DLF', 'ADANIGREEN', 'PIDILITIND', 'SIEMENS', 'HAVELLS', 'GODREJCP', 'AMBUJACEM', 'BERGEPAINT', 'DABUR',
    'INDIGO', 'GAIL', 'BANDHANBNK', 'IOC', 'CHOLAFIN', 'ICICIGI', 'BANKBARODA', 'VEDL', 'TORNTPHARM', 'NAUKRI',
    'LUPIN', 'BOSCHLTD', 'HDFCAMC', 'MCDOWELL-N', 'HINDPETRO', 'MOTHERSON', 'ZOMATO', 'DMART', 'COLPAL', 'MARICO',
    'PAGEIND', 'ABB', 'ALKEM', 'IRCTC', 'JUBLFOOD', 'TATAPOWER', 'MPHASIS', 'BAJAJHLDNG', 'BEL', 'PFC',
    'NMDC', 'CANBK', 'RECLTD', 'OFSS', 'ATGL', 'SAIL', 'GMRINFRA', 'CONCOR', 'CROMPTON', 'ASTRAL',
  };

  static const Set<String> nifty101to200 = {
    'ACC', 'AUROPHARMA', 'BALKRISIND', 'BATAINDIA', 'BIOCON', 'CADILAHC', 'CUMMINSIND', 'ESCORTS', 'EXIDEIND', 'FEDERALBNK',
    'GLENMARK', 'IDFCFIRSTB', 'INDUSTOWER', 'INTELLECT', 'JKCEMENT', 'JINDALSTEL', 'L&TFH', 'LICHSGFIN', 'MANAPPURAM', 'MFSL',
    'MINDTREE', 'MRF', 'NAM-INDIA', 'NATIONALUM', 'PERSISTENT', 'PEL', 'PNB', 'POLYCAB', 'RBLBANK', 'SRF',
    'SRTRANSFIN', 'SUNDARMFIN', 'SUPREMEIND', 'TVSMOTOR', 'UBL', 'UPL', 'VOLTAS', 'WHIRLPOOL', 'YESBANK', 'ZEEL',
    'ASHOKLEY', 'APLAPOLLO', 'BALRAMCHIN', 'CHAMBLFERT', 'COFORGE', 'CRISIL', 'DIXON', 'FLUOROCHEM', 'GICRE', 'GLAND',
    'GNFC', 'GSPL', 'IIFL', 'INDIACEM', 'INDIANB', 'IPCALAB', 'IRB', 'JSWENERGY', 'KAJARIACER', 'KEI',
    'KPITTECH', 'LALPATHLAB', 'LAURUSLABS', 'LTTS', 'METROPOLIS', 'MOTILALOFS', 'MUTHOOTFIN', 'NAVINFLUOR', 'OBEROIRLTY', 'OIL',
    'PIIND', 'POONAWALLA', 'PVRINOX', 'RELAXO', 'ROUTE', 'SBICARD', 'SCHAEFFLER', 'SHRIRAMFIN', 'SONACOMS', 'SYNGENE',
    'TATACHEM', 'TATACOMM', 'TATAELXSI', 'TATAINVEST', 'TIINDIA', 'TORNTPOWER', 'TTKPRESTIG', 'UJJIVAN', 'UNIONBANK',
  };

  /// Smallest Nifty index the symbol belongs to: 50, 100, 200, 500, or 0 (none).
  /// So N50 => 50, "in Nifty 100" => tier <= 100, etc.
  static int tier(String symbol) {
    final s = symbol.toUpperCase();
    if (nifty50.contains(s)) return 50;
    if (niftyNext50.contains(s)) return 100;
    if (nifty101to200.contains(s)) return 200;
    return 500; // remaining Nifty 500 constituents
  }
}
